template: Hello, %s!
defaultName: defName

server:
  rootPath: /api/
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: qweQWE123!@#
  url: jdbc:mysql://localhost:3306/appcenter?allowMultiQueries=true
  validationQuery: "/* Health Check */ SELECT 1"

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: ALL
  # This line stops org.hibernate.SQL (or anything under it) from using the root logger
  appenders:
    - type: file
      currentLogFilename: ./logs/example-sql.log
      archivedLogFilenamePattern: ./logs/example-sql-%d.log.gz
      archivedFileCount: 5