template: Hello, %s!
defaultName: defName

server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: qweQWE123!@#
  url: jdbc:mysql://localhost:3306/appcenter?allowMultiQueries=true
  validationQuery: "/* Health Check */ SELECT 1"